version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "cloud-poc-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5pakk1iskevu"
s3_prefix = "cloud-poc-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-poc-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5pakk1iskevu"
s3_prefix = "cloud-poc-stack"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
